uploads = []

[[generated]]
id = "0jbnoESWPLrRZPbMhqOV4"
uri = "file://attached_assets/test_rose.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sRTBUceYlp5P03aJhY2M2"
uri = "file://attached_assets/sky_test.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "epYAnmkQ0nvm1Y9-wDwst"
uri = "file://modern-tailors-website.zip"
type = "unspecified"
title = "Modern Tailors Website"

[[outputs]]
id = "0Qx29bcOtSJaZA1-MowjO"
uri = "file://modern-tailors-hostinger.zip"
type = "unspecified"
title = "Modern Tailors — Hostinger (updated)"

[[outputs]]
id = "CRNZ1cuyHefzfZ-sxLDZK"
uri = "file://modern-tailors-netlify.zip"
type = "unspecified"
title = "Modern Tailors — Netlify (updated)"
